### ISSUE TITLE
errors in browser console

### ISSUE THREAD

**Issue by peacemakr** [xirdev/xirsys-nodejs#2]
I slightly modified the server to use http

```
var server = http.createServer(app).listen(srvPort);
```

then, getting err in Chrome's console
```
xirsys.signal.js:238 WebSocket connection to 'wss://endpoint02.uswest.xirsys.com/ws/v2/....423rweq.....' failed: WebSocket opening handshake was cancelednext @ xirsys.signal.js:238
webrtc.html:294 error:  Event @ webrtc.html:294
http://192.168.1.x:8000/undefined Failed to load resource: the server responded with a status of 404 (Not Found)
webrtc.html:294 error:  undefined(anonymous function) @ webrtc.html:294
xirsys.signal.js:331 Uncaught TypeError: this.transport.send is not a function
    at constructor.send (http://192.168.1.x:8000/lib/xirsys.signal.js:331:28)
    at constructor.send (http://192.168.1.x:8000/lib/xirsys.signal.js:409:15)
    at HTMLFormElement.sendMessageEl.onsubmit (http://192.168.1.x:8000/webrtc.html:97:15)
```

Line numbers should be the same as in repo (didn't make any changes).

**Comment by peacemakr** [comment]
test.html works fine and is fetching data from Xirsys

**Comment by peacemakr** [comment]
any updates on this?

**Comment by jerrychabolla** [comment]
HI peacemakr, I am trying to reproduce your issue at the moment.  

Is there a reason you changed it to http?  As you might be aware, WebRTC will only work in a secure environment so the application will not be able to do a WebRTC video audio chat unless its https.

**Comment by peacemakr** [comment]
just wanted the scripts to come from a simple http server thats why.

iirc, the site is loaded on https (self-signed)

**Comment by jerrychabolla** [comment]
gotcha.

**Comment by peacemakr** [comment]
has it been fixed now?

**Comment by jerrychabolla** [comment]
Hey peacemakr,

Apologies for the wait I had to verify this before I could respond.  Unfortunately I was unable to reproduce your error.  After discussing with the devs, API calls currently work over HTTPS only.  I used the HTTPS module in node with a self-signed cert and the information comes in and connects the webrtc application perfectly.   You can contact experts@xirsys.com if you need any further assist on this peacemakr.  Many Thanks!

**Comment by peacemakr** [comment]
I tried with https but same error again.

here is what I am doing

I have an existing Express application in which I included the endpoints that you  have mentioned in your server.js file. And, from there I'm accessing Xirsys API to grab tokens, ice servers list etc.

My code seems to work since client is getting tokens and ice servers list. However, then I get the Websockets error.

For some reason, it is trying to access this /undefined path. 

That email address takes forever to get a response. I wish they had provided better documentation.

**Comment by peacemakr** [comment]
can I integrate the signalling server (assuming thats whats using web sockets for communication) into my express server? Any ideas, suggestions?
